services:
  planka:
    # Вместо image используем build, чтобы запечь ваши изменения кода
    build: 
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      # Сохраняем загруженные файлы (аватарки, вложения)
      - user-data:/app/data
      # НЕ монтируем код сервера, чтобы использовался скомпилированный код внутри контейнера
    ports:
      - 3000:1337
    environment:
      - BASE_URL=http://localhost:3000
      - DATABASE_URL=postgresql://postgres@postgres/planka
      - SECRET_KEY=change-this-random-string-to-something-very-long-and-secure
      
      # Язык по умолчанию
      - DEFAULT_LANGUAGE=ru-RU

      # Администратор по умолчанию (создастся при первом запуске)
      - DEFAULT_ADMIN_EMAIL=admin@admin.com
      - DEFAULT_ADMIN_PASSWORD=admin
      - DEFAULT_ADMIN_NAME=Admin
      - DEFAULT_ADMIN_USERNAME=admin
      
      # Настройки доверия прокси (если будете ставить Nginx перед Докером)
      - TRUST_PROXY=true

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planka"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  user-data:
  db-data: