services:
  planka:
    # Вместо image используем build, чтобы запечь ваши изменения кода
    # build: 
    #  context: .
    #  dockerfile: Dockerfile
    image: my-planka
    pull_policy: never
    restart: on-failure
    volumes:
      # Сохраняем загруженные файлы (аватарки, вложения)
      - user-data:/app/data
      # НЕ монтируем код сервера, чтобы использовался скомпилированный код внутри контейнера
    ports:
      - 3000:1337
    environment:
      - BASE_URL=http://172.16.244.210:3000
      - DATABASE_URL=postgresql://postgres:Zdrav53_Miac@postgres/planka
      - SECRET_KEY=301fc9842d7b840ff6a1f009046c311d7104fac7747af64dd38976c45decf2d17a55747f48bb927a8a72508c821d4e4388f5dfb2298a293112b4dc695439e539
      
      # Язык по умолчанию
      - DEFAULT_LANGUAGE=ru-RU

      # Администратор по умолчанию (создастся при первом запуске)
      - DEFAULT_ADMIN_EMAIL=leader@miac53.com
      - DEFAULT_ADMIN_PASSWORD=Zdrav53_Miac
      - DEFAULT_ADMIN_NAME=leader
      - DEFAULT_ADMIN_USERNAME=leader
      
      # Настройки доверия прокси (если будете ставить Nginx перед Докером)
      - TRUST_PROXY=true

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planka"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  user-data:
  db-data:
